### ISSUE TITLE
todo 

### ISSUE THREAD

**Issue by uxo2** [uxo2/articles#133]
## todo for this week about 3/8 to 3/12

- [ ] undo and redo snapshot.
- [ ] preview entry config.
- [ ] file lock and unlock.
- [ ] download file.
- [ ] file history.
- [ ] one step compile form axios bind.
- [ ] copy file(maybe add drag file).
- [ ] real preview environment.
- [ ] bug-fixed: file save and new folder or new file.
- [ ] workbench view and add tick marks.
- [ ] form constructor tree add copy, delete, clone func.
- [ ] vant-ui components workbench style optimization.
- [ ] multiple nesting row render and self-layout.
- [ ] vant component event bind.
- [ ] shortcut bind(shortcut dialog, preview view, redo, undo, downlaod)
