### ISSUE TITLE
todo about 3/15 - 3/19

### ISSUE THREAD

**Issue by uxo2** [uxo2/articles#134]
- [ ] 新建文件（或文件夹）触发多次自动保存bug
- [ ] 撤销、重做、清空功能优化
- [ ] 文件（表单）拖动接口联调（只允许文件拖动、不允许文件夹拖动）
- [ ] 文件复制粘贴接口联调（参考表单模板）
- [ ] 保存功能增加右键、快捷键绑定、enter保存文件（文件夹）
